apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moleculer-blog
	traefik.enable: true
	traefik.backend: www
	traefik.port: 4000
	traefik.frontend.entryPoints: http
	traefik.frontend.rule: PathPrefix:/
  name: moleculer-blog
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: moleculer-blog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: moleculer-blog
		traefik.enable: true
		traefik.backend: www
		traefik.port: 4000
		traefik.frontend.entryPoints: http
		traefik.frontend.rule: PathPrefix:/
    spec:
      containers:
        - env:
            - name: NODEID
              value: node-www
            - name: SERVICES
              value: www
            - name: PORT
              value: 4000
          image: moleculer-blog:1.0.0
          imagePullPolicy: Always
          name: moleculer-blog
          ports:
            - containerPort: 4000
              name: tcp
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '4'
              memory: 4Gi

	      image: 'redis:alpine'
          imagePullPolicy: Always
          name: redis
		  ports:
            - containerPort: 6379
              name: tcp
              protocol: TCP

	      image: 'nats:latest'
          imagePullPolicy: Always
          name: nats

	      image: 'mongo:latest'
          imagePullPolicy: Always
          name: mongo
		  
	      image: 'traefik:1.7'
          imagePullPolicy: Always
          name: traefik	
		  ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
			- containerPort: 8080
              name: tcp
              protocol: TCP
		  lifecycle:
            postStart:
              exec:
                command:
                  - "--web --docker --docker.domain=docker.localhost --logLevel=INFO
				  --docker.exposedbydefault=false"
		  volumeMounts:
            - mountPath: /var/run/docker.sock
              name: volume-image-docker\
			- mountPath: /traefik.toml
              name: volume-image-traefik

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: volume-image-docker
        - emptyDir: {}
          name: volume-image-traefik
